metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ${project.artifactId}
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.properties
              path: application.properties
      containers:
      - env:
        ports:
        - containerPort: 8090
          name : eiartifact
          protocol: TCP
        volumeMounts:
        - mountPath: "/deployments/config"
          name: config
        imagePullPolicy : Always
      imagePullSecrets:
      - name: registrypullsecret